services:
  - type: web
    name: hotel-management-live
    env: docker
    plan: free
    startCommand: "/usr/local/bin/entrypoint.sh"

    disk:
      name: hotel-storage
      mountPath: /var/www/html/storage/app/public
      sizeGB: 1

    envVars:
      - key: FILESYSTEM_DISK
        value: public
      - key: APP_URL
        value: https://hotel-management-bkt0.onrender.com
      - key: DOCUMENT_ROOT
        value: /var/www/html/public
