services:
  - type: web
    name: hotel-management-live
    env: docker
    plan: free
    startCommand: "/usr/local/bin/entrypoint.sh"

    disk:
      name: hotel-storage
      mountPath: /var/www/html/storage/app/public
      sizeGB: 1
    envVars:
      - key: DOCUMENT_ROOT
        value: /var/www/html/public
